-- MySQL Script generated by MySQL Workbench
-- Sun Apr 13 00:13:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT 'Thanos',
  `surname` VARCHAR(45) NOT NULL DEFAULT 'Mad Titan',
  `age` INT NULL,
  `country` VARCHAR(50) NOT NULL DEFAULT 'Ukraine',
  `city` VARCHAR(50) NOT NULL DEFAULT 'Kyiv',
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `description` VARCHAR(250) NULL,
  `image_path` VARCHAR(250) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `categories` VARCHAR(250) NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Requests` (
  `idRequests` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `description` VARCHAR(400) NULL,
  `image_path` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `state` INT NOT NULL DEFAULT 1,
  `categories` VARCHAR(300) NOT NULL DEFAULT '',
  `id_author` INT NOT NULL,
  PRIMARY KEY (`idRequests`),
  INDEX `fk_Requests_Users_idx` (`id_author` ASC) VISIBLE,
  CONSTRAINT `fk_Requests_Users`
    FOREIGN KEY (`id_author`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `idCategories` INT NOT NULL,
  `category` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequestCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RequestCategories` (
  `idRequest` INT NOT NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idRequest`, `idCategory`),
  INDEX `fk_RequestCategories_Category_idx` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_RequestCategories_Request`
    FOREIGN KEY (`idRequest`)
    REFERENCES `mydb`.`Requests` (`idRequests`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RequestCategories_Category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `mydb`.`Categories` (`idCategories`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
