"""init

Revision ID: 44ece2a015fc
Revises: 783a509744d3
Create Date: 2025-04-21 12:34:19.545915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ece2a015fc'
down_revision: Union[str, None] = '783a509744d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('Users', 'categories',
    #            existing_type=sa.VARCHAR(length=500),
    #            type_=sa.String(length=250),
    #            existing_nullable=True)
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('Users', 'categories',
    #            existing_type=sa.String(length=250),
    #            type_=sa.VARCHAR(length=500),
    #            existing_nullable=True)
    # # ### end Alembic commands ###
