"""Initial migration

Revision ID: 80e5eae1aa25
Revises:
Create Date: 2025-04-13 16:50:57.318980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80e5eae1aa25"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Requests")
    op.drop_table("Categories")
    op.drop_table("RequestCategories")
    op.drop_table("Users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Users",
        sa.Column("idUsers", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=45), nullable=False),
        sa.Column("surname", sa.VARCHAR(length=45), nullable=False),
        sa.Column("age", sa.INTEGER(), nullable=True),
        sa.Column("country", sa.VARCHAR(length=50), nullable=False),
        sa.Column("city", sa.VARCHAR(length=50), nullable=False),
        sa.Column("phone", sa.VARCHAR(length=45), nullable=True),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("description", sa.VARCHAR(length=250), nullable=True),
        sa.Column("image_path", sa.VARCHAR(length=250), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("categories", sa.VARCHAR(length=250), nullable=True),
        sa.PrimaryKeyConstraint("idUsers"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "RequestCategories",
        sa.Column("idRequest", sa.INTEGER(), nullable=False),
        sa.Column("idCategory", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["idCategory"],
            ["Categories.idCategories"],
        ),
        sa.ForeignKeyConstraint(
            ["idRequest"],
            ["Requests.idRequests"],
        ),
        sa.PrimaryKeyConstraint("idRequest", "idCategory"),
    )
    op.create_table(
        "Categories",
        sa.Column("idCategories", sa.INTEGER(), nullable=False),
        sa.Column("category", sa.VARCHAR(length=55), nullable=False),
        sa.PrimaryKeyConstraint("idCategories"),
    )
    op.create_table(
        "Requests",
        sa.Column("idRequests", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=70), nullable=False),
        sa.Column("description", sa.VARCHAR(length=400), nullable=True),
        sa.Column("image_path", sa.VARCHAR(length=255), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("state", sa.INTEGER(), nullable=False),
        sa.Column("id_author", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_author"],
            ["Users.idUsers"],
        ),
        sa.PrimaryKeyConstraint("idRequests"),
    )
    # ### end Alembic commands ###
